version: '3'
services:
  totp-web:
    image: busybox
    container_name: totp-web-blocks
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./:/var/www:ro
    command: httpd -f -p 80 -h /var/www
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    stop_grace_period: 1s
